#!/usr/bin/env python3.6
def feb(num):
    n=3
    a = 0
    b = 1
    if num == 1:
        print(a)
        retrun
    elif num == 2:
        print(f"{a} \n{b}")
        return
    print(f"{a} \n{b}")
    while n <= num:
        a, b = b, a+b
        print(f"{a} ")
        n +=1
feb(44)
