#!/usr/bin/env python3.6
import argparse
import sys

parser = argparse.ArgumentParser(description='file reversing')
parser.add_argument('filename', help="file name to reverse content")
parser.add_argument('--limit', '-l', type=int, help="Number of lins to read") # optiona parameter
parser.add_argument("--version", '-v', action='version', version='%(prog)s 2.0')
args = parser.parse_args()

try:
    f = open(args.filename)
    limit = args.limit
except FileNotFoundError as err:
    print(f"error: {err}")
    sys.exit(2)
else:
    with f:
        revfile = f.readlines()
        revfile.reverse()
#    print(revfile)
        if limit:
            revfile = revfile[:limit]
        for line in revfile:
            print(line.strip()[::-1])
finally:
    print("Finally")
